### ISSUE TITLE
Bat preview not working

### ISSUE THREAD

**Issue by zakissimo** [slavistan/lf-gadgets#12]
I'm trying to get the bat preview instead of cat for any text file. I changed the previewer file but the output is still the same.

```bash
# lf-ueberzug-previewer
-  *) cat "$file" ;;
+  *) bat "$file" ;;
```
![image](https://user-images.githubusercontent.com/64891486/158076916-3cf863fb-47c4-4d30-bc6a-04fac4c3bd40.png)
![image](https://user-images.githubusercontent.com/64891486/158076935-7a20683b-e95c-4601-9fcf-e9ae12430274.png)

**Comment by zakissimo** [comment]
Nevermind, I used "-f" to force colors and it works. (a bit slow but looks nice)

```bash
*) bat -f "$file" ;;
```
![image](https://user-images.githubusercontent.com/64891486/158077361-c7a0e098-a72f-4eb5-aeec-33d932df16b8.png)

Is there a way to make it fast ?

**Comment by slavistan** [comment]
@zakissimo I use `bat` for previews as well, and while it's noticeably slower to generate the preview than `cat`, it's still fast enough for me. You could check whether `bat` is the bottleneck in your setup or if there is some other configuration issue by running a few `bat` commands manually in the terminal in order to get a feel for the startup latency of `bat` vs `cat`. That latency is, of course, the best you'll get out of your lf previews.

If you're working on an older or slower machine take note that `bat` is orders of magnitude larger and more complex than `cat` (`ls -la /usr/bin/bat /usr/bin/cat`). This complexity comes at a price, which may be noticeable on lower-end machines.

**Comment by zakissimo** [comment]
Yes it's definitely my machine @slavistan . Thanks for your input and  sorry for the inconvenience .
